### ISSUE TITLE
Installation and Implementation of Prototype IRATI in Testbed FIBRE

### ISSUE THREAD

**Issue by DjalmaFilho-UFPE** [lbergesio/fibre-ocf#1]
Dear Leonardo,

I'm trying to implement the IRATI prototype experimentation network - https://fibre.org.br/, specifically OCF, but I'm having trouble when I finish the installation of the prototype. Because virtual machines are paravirtualized on XEN environment would like to know if there is any restriction to this environment. The installation of the prototype paravirtualizadas virtual machines on XEN feasible?

Thank attention!

**Comment by lbergesio** [comment]
answered in IRATI's site
